### ISSUE TITLE
Include images as a column feature

### ISSUE THREAD

**Issue by lucas-rdlr** [funkyheatmap/funkyheatmappy#8]
Hello,

First of all, thank you for your work. I trully find this heatmaps quite intersting to show results. I am not really experienced with it and I was wondering how should I create the "column_info" dataframe in order to include one column with images. I guess the "geom" column parameter should be set to "image" and inside the main dataframe "data" I have created a "logo" column with the paths to the figures I want to include, but this is not working.

I would like something similar to what they have here in the platform columns (Meta information)
![Screenshot from 2024-11-08 14-01-02](https://github.com/user-attachments/assets/a20fc8c3-9921-4ff7-ab6b-8b3cd52cf89c)

This is a preview of my main "data":
![Screenshot from 2024-11-08 14-03-12](https://github.com/user-attachments/assets/fb5a66d9-6386-4037-8127-58ad921a2ce3)

And this one of the "column_info":
![Screenshot from 2024-11-08 14-03-38](https://github.com/user-attachments/assets/bdd577d8-84cb-4a12-92a0-1da80bf5ebc1)

Without the "logo" column it works fine, but I get the problem when trying to add this new feature with images. There is no information in the API documentation about how this geom value should be treated, that is why I opened the issue.

Thank you in advance,
Lucas.

**Comment by LouiseDck** [comment]
Hi, thanks for the issue report!
The issue you have should be fixed in an upcoming release. In the meantine, could you try out the bugfix I pushed to `bugfix_images`

You can install it like so:
`pip install git+https://github.com/funkyheatmap/funkyheatmappy.git@bugfix_images`

It allows you to have the path to the logo in your data. In this version of anndata we required you to also specify a `path` and a `filetype` in the `column_info` options, but this is too restrictive.

I'll make sure this feature is better documenten on the new release.
Let me know if the bugfix branch solves your issue, or whether there's still something wrong.

**Comment by lucas-rdlr** [comment]
Hello !
I come back to give a positive report. This worked just perfect ! Thank you very much for the speed of the answer.
I can consider the issue solved :)
